### ISSUE TITLE
Color Segment lines

### ISSUE THREAD

**Issue by mkgoodie** [pearselab/tree-detection#1]
I am trying to color the segment lines to make them easier to see. Right now they show a gr color on a grayscale image. the code I attempted  is on line 93, you can test the code by running it on Sat_image using the call on line  103 @willpearse

**Comment by willpearse** [comment]
Thanks for this. I'm not exactly sure what the solution is, but I'm hopeful I can figure it out over the weekend... More soon...

**Comment by willpearse** [comment]
OK, so... I think I've got it figured out. I have a feeling you're going to scream, but please don't... Everything was essentially in place in what you had before, the only difference between that and what I've just pushed up here https://github.com/pearselab/tree-detection/commit/f4f1e18aa9dc05339d9dba95151cd52170869bda is that I've changed the direction of the threhsolding (`frame < th` not `frame > th`) such that the trees are the foreground, not the background.

Everything else in the function up there is your own code - I've just moved things around. So when we meet tomorrow, we can talk about how you're going to segment up the satellite images and get this puppy running on Pris!
